import type { PricingPlan, StatItem } from '@/types/global.types'

export const pricingPlans: PricingPlan[] = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Perfect for small learning businesses just getting started.',
    price_monthly: 29,
    price_yearly: 290,
    highlighted: false,
    features: [
      'Up to 500 students',
      'Up to 10 instructors',
      'Up to 50 courses',
      '5GB storage',
      'AI Basic (100 requests/day)',
      'Basic analytics',
      'Email support',
      'Standard video streaming',
    ],
    cta_text: 'Get Started',
    cta_link: '/register',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Best for growing learning businesses with advanced needs.',
    price_monthly: 79,
    price_yearly: 790,
    badge: 'Most Popular',
    highlighted: true,
    features: [
      'Up to 2,000 students',
      'Up to 50 instructors',
      'Unlimited courses',
      '50GB storage',
      'AI Pro (1,000 requests/day)',
      'Advanced analytics',
      'Priority email & chat support',
      'HLS adaptive streaming',
      'Custom domain',
      'API access',
    ],
    cta_text: 'Get Started',
    cta_link: '/register',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'For large organizations that need maximum power and flexibility.',
    price_monthly: 199,
    price_yearly: 1990,
    highlighted: false,
    features: [
      'Unlimited students',
      'Unlimited instructors',
      'Unlimited courses',
      '500GB+ storage',
      'AI Advanced (unlimited requests)',
      'Enterprise analytics & reporting',
      '24/7 priority support',
      'White-label branding',
      'Custom domain + SSL',
      'Full API + webhooks',
      'SCORM support',
      'Dedicated infrastructure',
    ],
    cta_text: 'Contact Sales',
    cta_link: '/register',
  },
]

export const stats: StatItem[] = [
  {
    id: 'students',
    value: '10000',
    label: 'Students',
    suffix: '+',
  },
  {
    id: 'courses',
    value: '500',
    label: 'Courses Created',
    suffix: '+',
  },
  {
    id: 'businesses',
    value: '50',
    label: 'Active Businesses',
    suffix: '+',
  },
  {
    id: 'uptime',
    value: '99.9',
    label: 'Uptime',
    suffix: '%',
  },
]
